### ISSUE TITLE
No Map and Dashboard Updates

### ISSUE THREAD

**Issue by fbausch** [simra-project/simra-project.github.io#5]
As it seems, neither the dashboard nor the maps are updated currently. The last updates were about three weeks ago.

At dashboard:
> Stand: 06.04.2023, 08:00:22

At Mannheim/Heidelberg/Ludwigshafen map:
> Karte generiert am April 3, 2023

**Comment by selphiron** [comment]
Thanks, I fixed it. There was an issue with the GitHub authentication.

**Comment by fbausch** [comment]
Hi,
the dashboards still don't get updated. As can be seen in https://github.com/simra-project/simra-project.github.io/tree/master/region the last update on Mannheim.json was last year April, while the Mannheim-meta.json was updated yesterday. This means that the data at https://simra-project.github.io/map.html?region=mannheim is outdated even though the popup says it's up to date.
